Use external checker

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,38 +23,38 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  check_update:
-    name: Check for Updates
-    runs-on: ubuntu-latest
-    outputs:
-      update: ${{ steps.check_update.outputs.res }}
-    steps:
-      - name: Check for Updates
-        id: check_update
-        shell: bash
-        run: |
-          if [ "${{ inputs.FORCE_REBUILD }}" = "true" ]; then
-            echo "FORCE_REBUILD is true, skipping update check"
-            echo "res=-1" >> "$GITHUB_OUTPUT"
-            exit
-          fi
+  # check_update:
+  #   name: Check for Updates
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     update: ${{ steps.check_update.outputs.res }}
+  #   steps:
+  #     - name: Check for Updates
+  #       id: check_update
+  #       shell: bash
+  #       run: |
+  #         if [ "${{ inputs.FORCE_REBUILD }}" = "true" ]; then
+  #           echo "FORCE_REBUILD is true, skipping update check"
+  #           echo "res=-1" >> "$GITHUB_OUTPUT"
+  #           exit
+  #         fi
 
-          # 'dnf check-update'
-          # exit codes:
-          #   0 - no updates
-          #   100 - updates available
-          #   125 - tag/platform not found
-          #   127 - command not found
-          res=0
-          podman run --quiet --rm ghcr.io/${{ github.repository_owner }}/blueshift_v3:10 dnf check-update || res=$?
-          echo "res=${res}" >> "$GITHUB_OUTPUT"
-          echo "Exit code: '$res'"
+  #         # 'dnf check-update'
+  #         # exit codes:
+  #         #   0 - no updates
+  #         #   100 - updates available
+  #         #   125 - tag/platform not found
+  #         #   127 - command not found
+  #         res=0
+  #         podman run --quiet --rm ghcr.io/${{ github.repository_owner }}/blueshift_v3:10 dnf check-update || res=$?
+  #         echo "res=${res}" >> "$GITHUB_OUTPUT"
+  #         echo "Exit code: '$res'"
 
   bluebuild:
     name: Build Custom Image
     runs-on: ubuntu-latest
-    needs: check_update
-    if: needs.check_update.outputs.update != '0'
+    # needs: check_update
+    # if: needs.check_update.outputs.update != '0'
     permissions:
       contents: read
       packages: write
@@ -67,9 +67,18 @@ jobs:
           - gnome
           - plasma
     steps:
+      - name: Check updates
+        id: check_update
+        uses: alexiri/update-image-action@main
+        with:
+          # !! Add your images here
+          imageref: ghcr.io/${{ github.repository_owner }}/${{ matrix.variant == 'gnome' && 'blueshift_v3' || 'blueshift_v3-plasma' }}
+          baseref: quay.io/almalinuxorg/almalinux-bootc:10-kitten
+
       # the build is fully handled by the reusable github action
       - name: Build Custom Image
-        if: false # temporarily disable this step
+        #if: false # temporarily disable this step
+        if: ${{ steps.check_update.outputs.rebuild-needed == 'true' }}
         uses: blue-build/github-action@v1.8
         with:
           recipe: recipe-${{ matrix.variant }}.yml
@@ -90,6 +99,7 @@ jobs:
       - name: Build ISO
         uses: alexiri/build-container-installer@pr-1
         id: build_iso
+        if: ${{ steps.check_update.outputs.rebuild-needed == 'true' }}
         with:
           arch: x86_64
           image_name: ${{ matrix.variant == 'gnome' && 'blueshift_v3' || 'blueshift_v3-plasma' }}
@@ -104,6 +114,8 @@ jobs:
       - name: Upload ISO as artifact
         id: upload
         uses: actions/upload-artifact@v4
+        needs: build_iso
+        if: needs.build_iso.outputs.iso_path
         with:
           name: ${{ steps.build_iso.outputs.iso_name }}
           path: |
